### ISSUE TITLE
PHP-Cache Project Redis supports PSR-16 and PSR-6 

### ISSUE THREAD

**Issue by prisis** [the-kbA-team/cache#1]
Hey :), 
all of the php-cache adapter supports psr-16, you can find the code in https://github.com/php-cache/cache/blob/master/src/Adapter/Common/AbstractCachePool.php

Can we make something better, or is something missing in the documentation?

**Comment by gregor-j** [comment]
You're right. I missed the `Psr\SimpleCache\CacheInterface`. I'll remove the part in the readme about php-cache not implementing PSR-16.
